#define CONFIG_AR7240 1
#define CONFIG_MACH_HORNET 1
#define CONFIG_HORNET_1_1_WAR 1
#define NEW_DDR_TAP_CAL 1
#define CONFIG_BOOTDELAY 1
#define CONFIG_DELAY_TO_AUTORUN_HTTPD		3
#define CONFIG_DELAY_TO_AUTORUN_CONSOLE		5
#define CONFIG_DELAY_TO_AUTORUN_NETCONSOLE	7
#define CONFIG_MAX_BUTTON_PRESSING 10
#define CFG_CONSOLE_INFO_QUIET

/* Automatically generated - do not edit */
#include <configs/ap121.h>
#define CONFIG_PID_MR302001		1
#define GPIO_INTERNET_LED_BIT	27
#define GPIO_INTERNET_LED_ON		0
#define GPIO_WPS_LED_BIT			26
#define GPIO_WPS_LED_ON			0
#define GPIO_WLAN_LED_BIT		0
#define GPIO_WLAN_LED_ON			1
#define GPIO_ETH_LED_BIT			17
#define GPIO_ETH_LED_ON			0
#define GPIO_RST_BUTTON_BIT		11
#define BOARD_CUSTOM_STRING		"AP121 (AR9331) U-Boot for TL-MR3020"
